export const projects = [
  {
    id: 1,
    title: "Creators Value",
    category: "Web Development",
    websiteLink: "https://creatorsvalue.com",
    image: "/projects/website.png",
    description:
      "Creators Value is your one-stop platform for editing, publishing, branding, and marketing services. We empower visionaries to bring their ideas to life and achieve success with innovative tools and expert support.",
    link: "/pages/project/creators-value",
    slug: "creators-value",
  },
  {
    id: 2,
    title: "FeatBooks",
    category: ["Publishing", "Web Development"],
    websiteLink: "https://featbooks.com",
    image: "/projects/campaign.jpg",
    description:
      "Our mission is to help authors, content creators, and storytellers by providing professional publishing and marketing services that bring their visions to life.",
    link: "/projects/featbooks",
    slug: "featbooks",
  },
  {
    id: 3,
    title: "KennethCobonPue",
    category: ["Corporate Profiles", "Web Development"],
    websiteLink: "https://kennethcobonpue.com",
    image: "/projects/identity.jpg",
    description:
      "KennethCobonPue is a furniture company renowned for its innovative and stylish designs, blending traditional craftsmanship with modern aesthetics to create unique and functional pieces.",
    link: "/project/kennethcobonpue",
    slug: "kennethcobonpue",
  },

  {
    id: 5,
    title: "NextART",
    category: ["Web Development"],
    websiteLink: "https://nextart.com",
    image: "/projects/booklet.png",
    description:
      "NextART is a platform for artists to showcase their work and connect with art enthusiasts, providing a space for creativity and expression.",
    link: "/projects/nextart",
    slug: "nextart",
  },

  {
    id: 7,
    title: "Event Poster",
    category: "Graphic Design",
    image: "/projects/graphic.jpg",
    description: "Creative event poster design",
    link: "/projects/event-poster",
  },
  {
    id: 8,
    title: "Mural Handuraw",
    category: "Murals",
    image: "/projects/murals.jpg",
    description:
      "Mural Handuraw is a mural project in the Philippines with a vibrant celebration of Filipino culture through street art, blending traditional elements with contemporary design.",
    link: "/pages/project/mural-handuraw",
    slug: "mural-handuraw",
  },
  {
    id: 9,
    title: "Product Photography",
    category: "Photography",

    image: "/projects/GEISHA.png",
    description: "High-quality product photography for e-commerce",
    link: "/pages/project/product-photography",
    slug: "product-photography",
  },
  {
    id: 11,
    title: "Youth for Livable Communities",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/youthforlivablecommunities",
    image: "/projects/categoriesAssets/SocialMedia/YLC.png",
    description:
      "Youth for Livable Communities is a social media campaign that aims to raise awareness about the importance of livable communities and encourage youth involvement in creating sustainable and vibrant urban environments.",
    link: "/projects/youth-for-livable-communities",
  },
  {
    id: 12,
    title: "Winnia Products International",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/indianfoodproducts",
    image: "/projects/categoriesAssets/SocialMedia/WINNIA FOOD PRODUCTS FB.png",
    description:
      "We have various Indian grocery items & Mediterenean spices. We also have Indian kurtis, bangles, acc",
    link: "/projects/winnia-products-international",
  },
  {
    id: 13,
    title: "Vegetarian Cooking Jam",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/vegetariancookingjam",
    image:
      "/projects/categoriesAssets/SocialMedia/VEGETARIAN COOKING JAM FB.png",
    description:
      "We have various Indian grocery items & Mediterenean spices. We also have Indian kurtis, bangles, acc",
    link: "/projects/vegetarian-cooking-jam",
  },
  {
    id: 14,
    title: "Romoza Home",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/romozahome",
    image: "/projects/categoriesAssets/SocialMedia/ROMOZA HOME FB.png",
    description:
      "Romoza Home offers a wide range of home decor products, including furniture, lighting, and accessories, to help you create a stylish and comfortable living space.",
    link: "/projects/romoza-home",
  },
  {
    id: 15,
    title: "Plan Out",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/planout.ph",
    image: "/projects/categoriesAssets/SocialMedia/PlanOut.png",
    description:
      "Plan Out is a social media campaign that helps individuals and organizations plan and organize events effectively, providing tools and resources for successful event management.",
    link: "/projects/plan-out",
  },
  {
    id: 16,
    title: "Paraiso Tropical",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/paraisotropical",
    image: "/projects/categoriesAssets/SocialMedia/paraisoTropicale.png",
    description:
      "Paraiso Tropical is a social media campaign that promotes the beauty and culture of tropical destinations, encouraging sustainable tourism and environmental conservation.",
    link: "/projects/paraiso-tropical",
  },
  {
    id: 17,
    title: "nextART",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/nextart.ph",
    image: "/projects/categoriesAssets/SocialMedia/NEXTART FB.png",
    description:
      "nextART is a vibrant platform for artists to connect and share their creative works with a wider audience.",
    link: "/projects/nextart",
  },
  {
    id: 18,
    title: "Miniso",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/miniso.ph",
    image: "/projects/categoriesAssets/SocialMedia/Miniso.png",
    description:
      "Miniso offers a wide range of affordable lifestyle products, bringing joy and convenience to everyday life.",
    link: "/projects/miniso",
  },
  {
    id: 19,
    title: "Luisa Robinson Atellier",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/luisarobinsonatellier",
    image: "/projects/categoriesAssets/SocialMedia/LUISA ROBINSON FB.png",
    description:
      "Luisa Robinson Atellier is a hub for exquisite fashion designs, blending elegance with modern trends.",
    link: "/projects/luisa-robinson-atellier",
  },
  {
    id: 20,
    title: "Kenneth Cobonpue",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/luisarobinsonatellier",
    image: "/projects/categoriesAssets/SocialMedia/KENNETH COBONPUE.png",
    description:
      "Kenneth Cobonpue is renowned for its innovative furniture designs that combine traditional craftsmanship with modern aesthetics.",
    link: "/projects/luisa-robinson-atellier",
  },
  {
    id: 21,
    title: "Celadon",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/kennethcobonpue",
    image: "/projects/categoriesAssets/SocialMedia/CELADON.png",
    description:
      "Celadon offers a unique collection of handcrafted ceramics, perfect for adding a touch of elegance to any space.",
    link: "/projects/kenneth-cobonpue",
  },
  {
    id: 22,
    title: "Beetzee",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/indianfoodproducts",
    image: "/projects/categoriesAssets/SocialMedia/Beetzee.png",
    description:
      "Beetzee is your go-to source for delicious and healthy beetroot-based products, promoting a nutritious lifestyle.",
    link: "/projects/winnia-products-international",
  },
  {
    id: 23,
    title: "Aspire",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/theartoflivingmozahome",
    image: "/projects/categoriesAssets/SocialMedia/Aspire.png",
    description:
      "Aspire is a motivational platform that inspires individuals to reach their full potential through personal development.",
    link: "/projects/the-art-of-living",
  },
  {
    id: 24,
    title: "Asia's Lashes Dumaguete",
    category: "Social Media",
    websiteLink: "https://www.facebook.com/theartoflivingmozahome",
    image: "/projects/categoriesAssets/SocialMedia/ACL.png",
    description:
      "Asia's Lashes Dumaguete offers premium eyelash extensions, enhancing your natural beauty with a touch of elegance.",
    link: "/projects/the-art-of-living",
  },
  {
    id: 25,
    title: "ZEN SIM",
    category: "Branding",
    image: "/projects/categoriesAssets/Brandings/images/zensim.jpg",
    pdf: "/projects/categoriesAssets/Brandings/BRANDING_ZEN SIM.pdf",
    description: "ZEN SIM",
    link: "/projects/zen-sim",
  },
  {
    id: 26,
    title: "VINS",
    category: "Branding",
    image: "/projects/categoriesAssets/Brandings/images/vins.png",
    pdf: "/projects/categoriesAssets/Brandings/BRANDING_VINS.pdf",
    description: "VINS",
    link: "/projects/vins",
  },
  {
    id: 27,
    title: "CHAD",
    category: "Branding",
    image: "/projects/categoriesAssets/Brandings/images/chad.jpg",
    pdf: "/projects/categoriesAssets/Brandings/BRANDING_CHAD.pdf",
    description: "CHAD",
    link: "/projects/chad",
  },
  {
    id: 28,
    title: "HIRAYA",
    category: "Branding",
    image: "/projects/categoriesAssets/Brandings/images/hiraya.png",
    pdf: "/projects/categoriesAssets/Brandings/BRANDING_HIRAYA.pdf",
    description: "HIRAYA",
    link: "/projects/hiraya",
  },
  {
    id: 29,
    title: "OUTLOUD",
    category: "Branding",
    image: "/projects/categoriesAssets/Brandings/images/outloud.png",
    pdf: "/projects/categoriesAssets/Brandings/BRANDING_OUTLOUD.pdf",
    description: "OUTLOUD",
    link: "/projects/outloud",
  },
  {
    id: 30,
    title: "TROPEKO",
    category: "Branding",
    image: "/projects/categoriesAssets/Brandings/images/tropeko.png",
    pdf: "/projects/categoriesAssets/Brandings/BRANDING_TROPEKO.pdf",
    description: "TROPEKO",
    link: "/projects/bench",
  },
  {
    id: 31,
    title: "Handuraw",
    category: "Murals",
    image: "/projects/categoriesAssets/murals/handuraw/image1.jpg",
    description: "Handuraw",
    link: "/projects/handuraw",
  },
  {
    id: 32,
    title: "Handuraw",
    category: "Murals",
    image: "/projects/categoriesAssets/murals/handuraw/image2.png",
    description: "Handuraw",
    link: "/projects/handuraw",
  },
  {
    id: 33,
    title: "Handuraw",
    category: "Murals",
    image: "/projects/categoriesAssets/murals/handuraw/image3.jpg",
    description: "Handuraw",
    link: "/projects/handuraw",
  },
  {
    id: 34,
    title: "Handuraw",
    category: "Murals",
    image: "/projects/categoriesAssets/murals/handuraw/image4.jpg",
    description: "Handuraw",
    link: "/projects/handuraw",
  },
  {
    id: 35,
    title: "Handuraw",
    category: "Murals",
    image: "/projects/categoriesAssets/murals/handuraw/image5.jpg",
    description: "Handuraw",
    link: "/projects/handuraw",
  },

  {
    id: 37,
    title: "Handuraw",
    category: "Murals",
    image: "/projects/categoriesAssets/murals/handuraw/image7.jpg",
    description: "Handuraw",
    link: "/projects/handuraw",
  },
  {
    id: 38,
    title: "Handuraw",
    category: "Murals",
    image: "/projects/categoriesAssets/murals/handuraw/image8.jpg",
    description: "Handuraw",
    link: "/projects/handuraw",
  },
  {
    id: 39,
    title: "Handuraw",
    category: "Murals",
    image: "/projects/categoriesAssets/murals/handuraw/image9.jpg",
    description: "Handuraw",
    link: "/projects/handuraw",
  },
  {
    id: 40,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/FSCreativeTeam.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 41,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/FSCreativeTeam1.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 42,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/KennethCobonpue1.png",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 43,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/KennethCobonpue2.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 44,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/KennethCobonpue3.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 45,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/POSTER_MOVIE1.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 46,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/POSTER_MOVIE2.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 47,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/sd+cCRIS.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 48,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/sd+cSHENAE.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 49,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/sd+cYUKA.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 50,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/Speedy11.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 51,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/Speedy12.png",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 52,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/Speedy13.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 53,
    title: "Graphic Designs",
    category: "Graphic Design",
    image: "/projects/categoriesAssets/graphicDesigns/TROPEKO.jpg",
    description: "Graphic Designs",
    link: "/projects/graphic-designs",
  },
  {
    id: 54,
    title: "CLOUDS",
    category: "Creative Marketing",
    image: "/projects/categoriesAssets/creativeMarketing/CLOUDS.jpg",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
  {
    id: 55,
    title: "COCOON",
    category: "Creative Marketing",
    image: "/projects/categoriesAssets/creativeMarketing/COCOON.jpg",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
  {
    id: 56,
    title: "CU CME",
    category: "Creative Marketing",
    image: "/projects/categoriesAssets/creativeMarketing/CU CME.jpg",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
  {
    id: 57,
    title: "DRAGON_S TAIL",
    category: "Creative Marketing",
    image: "/projects/categoriesAssets/creativeMarketing/DRAGON_S TAIL 2.jpg",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
  {
    id: 58,
    title: "DRAGON_S TAIL",
    category: "Creative Marketing",
    image: "/projects/categoriesAssets/creativeMarketing/DRAGON_S TAIL.jpg",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
  {
    id: 59,
    title: "GEISHA",
    category: "Creative Marketing",
    image: "/projects/categoriesAssets/creativeMarketing/GEISHA.png",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
  {
    id: 60,
    title: "HALO",
    category: "Creative Marketing",
    image: "/projects/categoriesAssets/creativeMarketing/HALO.jpg",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
  {
    id: 61,
    title: "KAI ARC LAMP",
    category: "Creative Marketing",
    image: "/projects/categoriesAssets/creativeMarketing/KAI ARC LAMP.jpg",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
  {
    id: 62,
    title: "Creative Marketing",
    category: "KNOT",
    image: "/projects/categoriesAssets/creativeMarketing/KNOT.jpg",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
  {
    id: 63,
    title: "Creative Marketing",
    category: "Creative Marketing",
    image:
      "/projects/categoriesAssets/creativeMarketing/LITTLE PEOPLE Screen.jpg",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
  {
    id: 64,
    title: "Creative Marketing",
    category: "Creative Marketing",
    image: "/projects/categoriesAssets/creativeMarketing/LITTLE PEOPLE.jpg",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
  {
    id: 65,
    title: "SAFARI",
    category: "Creative Marketing",
    image: "/projects/categoriesAssets/creativeMarketing/SAFARI.jpg",
    description: "Creative Marketing",
    link: "/projects/creative-marketing",
  },
];
