export const portfolioImages = [
  {
    id: 1,
    src: "/projects/photography/SAFARI.jpg",
    alt: "Safari",
    category: "product",
    client: "Safari",
    description: "Safari chairs",
    impact: "40% increase in online sales",
  },
  {
    id: 2,
    src: "/projects/photography/LITTLE PEOPLE.jpg",
    alt: "Little People",
    category: "product",
    client: "Little People",
    description: "Little People",
    impact: "Featured in beauty magazines",
  },
  {
    id: 3,
    src: "/projects/photography/KNOT.jpg",
    alt: "Knot",
    category: "product",
    client: "Knot",
    description: "Knot",
    impact: "Featured in beauty magazines",
  },
  {
    id: 4,
    src: "/projects/photography/KAI ARC LAMP.jpg",
    alt: "Kai Arc Lamp",
    category: "product",
    client: "Kai Arc Lamp",
    description: "Kai Arc Lamp",
    impact: "Featured in beauty magazines",
  },
  {
    id: 5,
    src: "/projects/photography/HALO.jpg",
    alt: "Halo",
    category: "product",
    client: "Halo",
    description: "Halo",
    impact: "Featured in beauty magazines",
  },
  {
    id: 6,
    src: "/projects/photography/GEISHA.png",
    alt: "Geisha",
    category: "lifestyle",
    client: "Geisha",
    description: "Geisha",
    impact: "Featured in beauty magazines",
  },
  {
    id: 7,
    src: "/projects/photography/DRAGON_S TAIL 2.jpg",
    alt: "Dragon's Tail",
    category: "product",
    client: "Dragon's Tail",
    description: "Dragon's Tail",
    impact: "Featured in beauty magazines",
  },
  {
    id: 8,
    src: "/projects/photography/CU CME.jpg",
    alt: "CU CME",
    category: "product",
    client: "CU CME",
    description: "CU CME",
    impact: "Featured in beauty magazines",
  },
  {
    id: 9,
    src: "/projects/photography/COCOON.jpg",
    alt: "Cocooon",
    category: "product",
    client: "Cocooon",
    description: "Cocooon",
    impact: "Featured in beauty magazines",
  },
  {
    id: 10,
    src: "/projects/photography/CLOUDS.jpg",
    alt: "Clouds",
    category: "product",
    client: "Clouds",
    description: "Clouds",
    impact: "Featured in beauty magazines",
  },
];

export const photographyCategories = [
  "all",
  "product",
  "food",
  "corporate",
  "events",
  "lifestyle",
];

export const photographyServices = [
  {
    title: "Product Photography",
    description: "High-quality product shots that drive sales",
    features: [
      "360° product views",
      "Lifestyle product shots",
      "White background photography",
      "Creative product styling",
    ],
  },
  {
    title: "Food Photography",
    description: "Appetizing food shots for restaurants and brands",
    features: [
      "Menu photography",
      "Food packaging shots",
      "Restaurant ambiance",
      "Social media content",
    ],
  },
  {
    title: "Corporate Photography",
    description: "Professional corporate imagery",
    features: [
      "Corporate headshots",
      "Office environment",
      "Event coverage",
      "Brand storytelling",
    ],
  },
];
